# LLM and deployment for the AI that converses with the user:
model_id: "gpt-4"
deployment_name: "test-chatbot"
api_base: "https://gpt4-for-trusting.openai.azure.com/"
api_version: "2023-05-15"
api_type: "azure"
# Dictionary that maps LLM to deployment which implements that
model_to_deployment_map:
  gpt-4: "test-chatbot"
  gpt-35-turbo-16k: "gpt-35-turbo-16k"