model_id_available: ["gpt-3.5-turbo", "gpt-4"]
model_id: "gpt-3.5-turbo"
model_id_source_fidelity: "gpt-3.5-turbo"
api_base: "https://gpt4-for-trusting.openai.azure.com/"
deployment_name: "test-chatbot"
api_version: "2023-05-15"
api_type: "azure"