# Define chatbots and their respective modes and judges
chatbots:
  mental_health:
    response_type:
      default_mode:
        preliminary_judges:
          swift_judge_role_and_emergency_contact:
            evaluation_keywords: [DENY, WARNING, ACCEPT]
            prompt_variables: [user_message, chatbot_message]
          swift_judge_disclaimer_check:
            evaluation_keywords: [DENY, AGREE]
            prompt_variables: [user_message, chatbot_message]
        chief_judges:
          chief_judge_default:
            evaluation_keywords: [REJECT, WARNING, ACCEPT]
            prompt_variables: [user_message, chatbot_message]

      source_communication:
        preliminary_judges:
          swift_judge_source_fidelity:
            evaluation_keywords: [DENY, AGREE]
            prompt_variables: [source, chatbot_message]
        chief_judges:
          chief_judge_source_fidelity:
            evaluation_keywords: [REJECT, WARNING, ACCEPT]
            prompt_variables: [source, chatbot_message]

  e_companion:
    response_type:
      default:
        stages:
          preliminary_judges:
            - swift_source_check
          chief_judge: chief_judge_default
        default_mode:
          stages:
            preliminary_judges:
              - swift_role_check
              - swift_disclaimer_check
            chief_judge: chief_judge_default
