# Define chatbots and their respective modes and judges. The structure is
# [chatbot][AI-filter-stage][dictionary-specifying each AI-agent].
# Each judge is triggered by a set of citations; these citation groups are
# defined in 'citations.yaml'. If you want to skip a certain AI-filter stage is
# not desired, such as 'chatbot_response_modifiers', set it to an empty list.

# *** SUPPORT AGENTS FOR SCHIZOPHRENIA CHATBOT ***
mental_health:
  # AI-judges that use GPT-3.5
  preliminary_judges:
    - name: swift_judge_role_and_emergency_contact
      prompt_variables: [user_message, chatbot_message]
      associated_mode: default
      verdict:
        DENY: REJECT
        WARNING: REJECT
        ACCEPT: ACCEPT
    - name: swift_judge_disclaimer_check
      prompt_variables: [user_message, chatbot_message]
      associated_mode: default
      verdict:
        DENY: REJECT
        AGREE: ACCEPT
    - name: swift_judge_source_fidelity
      prompt_variables: [source, chatbot_message]
      associated_mode: source_communication
      verdict:
        NOT SUPPORTED: REJECT
        SUPPORTED: ACCEPT
  # Final verdict AI-judges that use GPT-4
  chief_judges:
    - name: chief_judge_default
      evaluation_keywords: ["REJECT", "WARNING", "ACCEPT"]
      prompt_variables: [user_message, chatbot_message]
      associated_mode: default
      verdict:
        REJECT: REJECT
        WARNING: WARNING
        ACCEPT: ACCEPT
    - name: chief_judge_source_fidelity
      evaluation_keywords: ["REJECT", "WARNING", "ACCEPT"]
      prompt_variables: [sources, chatbot_message]
      associated_mode: source_communication
  # AI-agents that modifies the chatbots response (potentially using outputs
  # from AI-monitors)
  chatbot_response_modifiers:
    - name: compliance_enforcer
      prompt_variables: [user_message, chatbot_message, system_message]
  # AI-agents that check if the user has confirmed that they want to be
  # redirected
  redirect_consent_checkers:
    - name: referral_consent_checker
      prompt_variables: [last_2_messages]
      evaluation_keywords: ["FALSE", "TRUE"]

# *** SUPPORT AGENTS FOR E-HEALTH CHATBOT ***
ehealth_module1:
  # AI-judges that use GPT-3.5
  preliminary_judges: []
  # Final verdict AI-judges that use GPT-4
  chief_judges: []
  # AI-agents that modifies the chatbots response (set to [] if not wanted)
  chatbot_response_modifiers: []
  # AI-agents that check if the user has confirmed that they want to be
  # redirected
  redirect_consent_checkers: []
