# Define chatbots and their respective modes and judges. Each judge is triggered
# by a set of citations; these sets are defined in 'response_types.yaml'
chatbots:
  mental_health:
    # AI-judges that use GPT-3.5
    preliminary_judges:
      swift_judge_role_and_emergency_contact:
        evaluation_keywords: [DENY, WARNING, ACCEPT]
        prompt_variables: [user_message, chatbot_message]
        associated_mode: default
      swift_judge_disclaimer_check:
        evaluation_keywords: [DENY, AGREE]
        prompt_variables: [user_message, chatbot_message]
        associated_mode: default
      swift_judge_source_fidelity:
        evaluation_keywords: [NOT SUPPORTED, SUPPORTED]
        prompt_variables: [source, chatbot_message]
        associated_mode: source_communication
    # Final verdict AI-judges that use GPT-4
    chief_judges:
      chief_judge_default:
        evaluation_keywords: [REJECT, WARNING, ACCEPT]
        prompt_variables: [user_message, chatbot_message]
        associated_mode: default
      chief_judge_source_fidelity:
        evaluation_keywords: [REJECT, WARNING, ACCEPT]
        prompt_variables: [sources, chatbot_message]
        associated_mode: source_communication
