word_wrap: 80  # N.o. characters before line gets wrapped.
plot_duration: 10000
max_tokens_before_summary: 30000
# Verbosity: control what gets printed in the console
print_sources: False
print_inactivity_times: True
print_when_information_is_inserted: True
