word_wrap: 80  # N.o. characters before line gets wrapped.
plot_duration: 10000  # The duration of time for which the figures are shown (uggly solution...)
max_tokens_before_truncation: 4000  # Determines maximum length before chat gets truncated
inactivity_threshold: 2  # Remove source from conversation if it has not been cited in the last ... messages
n_attempts_at_producing_valid_response: 1
max_requests: 2
# Printing
print_knowledge_requests: True
# Pricing info
dollars_per_1k_input_token: 0.03
dollars_per_1k_output_token: 0.06
nok_per_dollar: 10.6  # rate: NOK per Dollar
max_tokens_per_message: 250  # Limit in prompt + margin
max_tokens_hard_upper_limit: 270  # This is an argument in ChatCompletion.create() used to
# estimate token consumption rate and truncate messages. Set abit higher to avoid truncation due to
# differences in how N-tokens is counted
soft_limit_1_tokens_per_message: 150  # Mild warning
soft_limit_2_tokens_per_message: 200  # More severe warning
hard_limit_tokens_per_message: 250  # Bot must redo message if this limit is exceeded
warning_limit_tokens_per_message: 150
# --- OVERSEER BOTS ---
enable_overseer_filter: True
enable_hard_coded_filter: True