word_wrap: 80  # N.o. characters before line gets wrapped.
plot_duration: 10000  # The duration of time for which the figures are shown (uggly solution...)
max_tokens_before_truncation: 3000  # Determines maximum length before chat gets truncated
inactivity_threshold: 2  # Remove source from conversation if it has not been cited in the last ... messages
n_attempts_at_producing_valid_response: 1
max_requests: 2
# Printing
print_knowledge_requests: True
# Pricing info
dollars_per_1k_input_token: 0.03
dollars_per_1k_output_token: 0.06
kr_to_dollar_ratio: 0.096  # rate of kr to dollars
max_tokens_per_message: 250  # Limit in prompt + margin
warning_limit_tokens_per_message: 150